#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


echo "Running migrations..."
python manage.py migrate

echo "Starting marimo"
exec marimo edit &> /dev/null & # Ignora a saida mandando para /dev/null

echo "Starting tailwindcss watcher"
exec npx tailwindcss -i ./imperial/static/css/input.css -o ./imperial/static/css/output.css --watch=always &

echo "Starting runserver"
exec python manage.py runserver 0.0.0.0:8000
