services: 
  web:
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: imperial_local
    container_name: imperial_local
    volumes:
      - .:/app:z
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: /start